name: Maven Central Publish Release
on:
  release:
    types:
      - published

jobs:
  publish-release:
    if: ${{ !github.event.release.prerelease }} # Don't run this on prerelease
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
